# Generated by Django 3.0.5 on 2020-05-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lasting',
            new_name='Listing',
        ),
    ]
